name: learn-github-actions
on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
	uses: actions/checkout@v4
      - name: write greeting to txt file 
	run: echo 'hello world!' > greeting.txt
      - name: check that txt file is there
	run: ls -la 
      - name: greet
	run: cat greeting.txt
	 
